### ISSUE TITLE
Missing files error when executing _runSimulation_

### ISSUE THREAD

**Issue by giahuytn** [kit-ifv/mobitopp-matsim-coupling#1]
hi guys,

I am trying to explore this repository to understand how to integrate Mobitopp and MATsim libraries. It seems that the source code is outdated, I have to modify the source code a bit (based on the Mobitopp repository example) to be able to compile and run **_runPopulationSynthesis_** successfully. But it still throws an error since running**_runSimulation_** gradle script due to missing 3 files: 102_pkw_w. mtx, 104_pkw_ex.mtx and stuttgart_2009_everkehrsraum_nutzung.net.bz2. These files are configured in **_data/simulation.yam_** . Could you give me what is wrong or how to get these files.

Thanks  a lot.

**Comment by maocatherine** [comment]
Hi,

I ran into similar confusion and here is what I do.

- The two mtx files are to create the external demand on top of the population. It looks to me is to scale up the demand as the synthetic population is seen as a sample of actual population. You could comment the createExternalDemand method and write another method similar to its logic.
- The net file you can reuse the one from the Mobitopp repository example. It works for me.

Cath

**Comment by giahuytn** [comment]
Thanks @maocatherine 
I did comment the**createExternalDemand** method  and it worked for me.
